### PR TITLE
refactor: upgrade go mod to `image-spec v1.1.0-rc4` and fix the missing types

### PR DESCRIPTION
**Pull request by Wwwsylvia**
Resolves: #530

### CODE REVIEW

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Comment by saschagrunert** [comment]
Hey folks, are you happy to cut a new release of this library after this merge?

**Comment by shizhMSFT** [comment]
@saschagrunert [`v2.2.1`](https://github.com/oras-project/oras-go/releases/tag/v2.2.1) was released with this PR change included.

**Comment by saschagrunert** [comment]
Thank you @shizhMSFT!

**Comment by FeynmanZhou** [comment]
@saschagrunert May I know which project you are going to integrate ORAS-go v2.2.1 with?

**Comment by saschagrunert** [comment]
@FeynmanZhou we're using it within the Security Profiles Operator: https://github.com/kubernetes-sigs/security-profiles-operator

**Comment by FeynmanZhou** [comment]
> @FeynmanZhou we're using it within the Security Profiles Operator: https://github.com/kubernetes-sigs/security-profiles-operator

Thanks @saschagrunert for sharing it. I noticed the use case of the Security Profiles Operator from your [K8s blog](https://kubernetes.io/blog/2023/05/24/oci-security-profiles/#oci-artifacts-to-the-rescue). Glad to see ORAS was adopted by SPO to manage OCI artifacts.

**Pull request merged**
