### PR TITLE
Code Tour

### PR DESCRIPTION
**Pull request by shizhMSFT**
Use vscode [CodeTour](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour) extension to view the code tour.

### CODE REVIEW

**Review by sajayantony — APPROVED** [review]
LGTM

**Comment by sajayantony** [comment]
@SteveLasker - as per the discussion - the recommendation is to keep tooling files out of the repositories unless there is a direct dependency.

**Comment by jdolitsky** [comment]
Where do we stand with this? Happy to merge, but sounds like @sajayantony 's last comment is to drop it?

**Comment by sajayantony** [comment]
@shizhMSFT whats your opinion given the refactor. Should we drop this?

**Comment by shizhMSFT** [comment]
Let's drop this as it is outdated.

**Pull request closed without merging**
