### PR TITLE
bump docker/distribution to v2.8.1

### PR DESCRIPTION
**Pull request by mihaibuzgau**
Bump docker/distribution to address [CWE-843](https://cwe.mitre.org/data/definitions/843.html)

### CODE REVIEW

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Comment by mihaibuzgau** [comment]
thanks @shizhMSFT for merging this!

Are you still planning to release v1? if so, when can we get a new tag?

**Comment by shizhMSFT** [comment]
@FeynmanZhou Could you help with the next release of `v1`?

**Comment by FeynmanZhou** [comment]
Hi @mihaibuzgau ,

Thanks for contributing to ORAS-go. Considering [ORAS-go v2](https://github.com/oras-project/oras-go#v2-experimental) is still experimental, ORAS-go v1 will be maintained by the ORAS community until ORAS v2 GA. Currently, ORAS-go v1 is not under active development, thus the ORAS community will only publish new releases to include necessary fixes at a low rate.

This [CWE-843](https://cwe.mitre.org/data/definitions/843.html) fix is significant and it is only existing in v1. ORAS v2 has no dependency on the docker/distribution. We can prepare a new release for v1 to include this fix.

**Comment by mihaibuzgau** [comment]
sounds good. Thanks @FeynmanZhou and @shizhMSFT !

**Pull request merged**
