### PR TITLE
add annotations to the advanced example

### PR DESCRIPTION
**Pull request by luisdavim**
This relates to #22 

here's the result:

```console
$ cat annotations.json                                                                                                                    
{
  "$config": {
    "hello": "world"
  },
  "$manifest": {
    "foo": "bar"
  },
  "cake.txt": {
    "fun": "more cream"
  }
}
```

```console
$ ./advanced copy my-repo/oso-plugins:cake --from files --to registry cake.txt --manifest-annotations annotations.json
Config annotation: map[hello:world]
Manifest annotation: map[foo:bar]
Adding: v1.Descriptor{MediaType:"application/vnd.oci.image.layer.v1.tar", Digest:"sha256:f5244e13720ccfb68afc0112821207fee6f4c14a65f634e1ab7be136f27ee433", Size:9, URLs:[]string(nil), Annotations:map[string]string{"fun":"more cream", "org.opencontainers.image.title":"cake.txt"}, Platform:(*v1.Platform)(nil)}
        map[string]string{"fun":"more cream", "org.opencontainers.image.title":"cake.txt"}
WARN[0000] reference for unknown type: application/vnd.unknown.config.v1+json 
Copied: v1.Descriptor{MediaType:"application/vnd.oci.image.manifest.v1+json", Digest:"sha256:9b620637369e6299c4eff2d8a99e6728e10f8e1b3711cc1fb918232e1a87f284", Size:412, URLs:[]string(nil), Annotations:map[string]string(nil), Platform:(*v1.Platform)(nil)}
        map[string]string(nil)
```

```console
$ curl -sL -u"user:pass" https://my-repo/v2/oso-plugins/manifests/cake | jq .      
{
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.unknown.config.v1+json",
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "size": 0
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:f5244e13720ccfb68afc0112821207fee6f4c14a65f634e1ab7be136f27ee433",
      "size": 9,
      "annotations": {
        "fun": "more cream",
        "org.opencontainers.image.title": "cake.txt"
      }
    }
  ]
}
```

### CODE REVIEW

**Comment by deitch** [comment]
Is your `annotations.json` just `{"org.opencontainers.image.title":"cake.txt"}`?

**Comment by luisdavim** [comment]
Sorry,  I was loading the files before reading the annotations, I've fixed that and updated the description, the layer annotations are working fine, the issue is only with the manifest annotations.
With `Push()`/`Pull()` I was able to get them to the repo, but the resulting descriptor would not have them when pulling and now, with `Copy()` I can't even get the manifest annotations uploaded.

**Comment by deitch** [comment]
OK, I think I see what is going on here. Let's bring the discussion back to the issue.

btw, I like the idea of adding annotations to the copy example; we need to fix some things first, and I am not sure I prefer a file over explicit key-value pairs.

**Comment by deitch** [comment]
I found the json format a bit overbearing, just for an example, so I replaced it with `key=value,key=value` options on the fly in #25 

I think we can close this one out @luisdavim ?

**Comment by luisdavim** [comment]
> I think we can close this one out @luisdavim ?

Sure, thanks 👍

**Pull request closed without merging**
