### PR TITLE
fix: check empty registry name

### LINKED ISSUE #698: BUG: `registry.ParseReference` returns false positive when registry is empty
Below code is expected to panic but can parse the invalid reference `/oras`
```golang
package main

import (
	"fmt"

	_ "crypto/sha256"

	"oras.land/oras-go/v2/registry"
)

func main() {
	rawRef := "/oras"
	ref, err := registry.ParseReference(rawRef)
	if err != nil {
		panic(err)
	}

	fmt.Println("Registry:", ref.Registry)
	fmt.Println("Repository:", ref.Repository)
} 
```
Version: oras.land/oras-go/v2 v2.4.0

The root cause is [url.ParseRequestURI](https://pkg.go.dev/net/url#ParseRequestURI) allows empty domain name, ORAS-go should enforce the non-empty checking.

### PR DESCRIPTION
**Pull request by shizhMSFT**
Fix #698

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Review by qweeah — APPROVED** [review]
LGTM although IANAM

**Comment by wangxiaoxuan273** [comment]
LGTM although IANAM

**Review by Wwwsylvia — APPROVED** [review]
LGTM

**Pull request merged**
