### PR TITLE
build: update to Go 1.18

### PR DESCRIPTION
**Pull request by lucacome**
Bumps go to 1.18 for `v1`

### CODE REVIEW

**Comment by shizhMSFT** [comment]
Since this is library code, adopters may still use older golang versions. We need to be careful on bumping up go versions.

@jdolitsky @deitch Do you have any inputs?

**Comment by TerryHowe** [comment]
Close this maybe?

**Comment by shizhMSFT** [comment]
> Close this maybe?

We plan to close it after releasing `oras-go v2.0.0`.

**Comment by lucacome** [comment]
> We plan to close it after releasing oras-go v2.0.0.

I've updated the PR, but re-reading this now I'm not sure if the plan is to merge it or just close it 😅

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Pull request merged**
