### PR TITLE
add options to save layers and root manifest; remove unused opts

### LINKED ISSUE #22: Missing manifest annotations.
I don't know if I'm doing anything wrong, but I've used `oras.WithManifestAnnotations()` to push my artefact with some metadata, that worked well because if I curl the repo directly I see it there:

```console
$ curl -sL -u"user:pass" https://my-repo/v2/oso-plugins/manifests/oso-legacy | jq .
{
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.unknown.config.v1+json",
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "size": 2
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:8e985dc2c81bd5e8bfafb2858b9a9cb420c02a29d5a96f32eb00f5850556410a",
      "size": 755,
      "annotations": {
        "hook": "chmod +x ~/.oso/bin/oso-legacy",
        "org.opencontainers.image.title": "oso-legacy"
      }
    }
  ],
  "annotations": {
    "caveats": "to get auto-completions do this...",
    "description": "a bridge to the past",
    "shortDescription": "a plugin"
  }
}
```

But then when I pull it using `desc, artefacts, err :=  oras.Pull(...)` I can loop through the artefacts and get the annotations from each of them, but `desc.Annotations` is empty...

The result of `fmt.Println(desc.Annotations)` is:

```
Annotations: map[]
```

### PR DESCRIPTION
**Pull request by deitch**
Fixes #22 

cc @luisdavim 

I suspect this may need to be rebased after #25 is in, which should go first.

### CODE REVIEW

**Comment by deitch** [comment]
I take it back. Either can go in first. The other may need to be rebased.

**Comment by luisdavim** [comment]
This makes it easier to get the manifests, but I don't think it fixes #22 the root manifest will still be missing the annotations.
I think the problem is the registry resolver never sets them : https://github.com/containerd/containerd/blob/main/remotes/docker/resolver.go#L375-L379

Printing the resulting manifests gives me:

```
{application/vnd.oci.image.manifest.v1+json sha256:48c94bcc5e55cea1b9bf75034d6713d93f009d57a4c64d192dac28d3acfe2ad5 611 [] map[] <nil>}
{application/vnd.oci.image.layer.v1.tar sha256:101db5834138c934950018314a6fca16cb997596bcb8555d7327aafdb29f4683 888 [] map[hook:cat ${OSO_CACHE}/plugins.json | jq . org.opencontainers.image.title:oso-legacy] <nil>}
```

Note the empty `map` but the actual manifest has annotations:

```console
$ curl -sL -u"user:pass" https://my-repo/v2/oso-plugins/manifests/oso-legacy | jq .
{
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.unknown.config.v1+json",
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "size": 2
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:101db5834138c934950018314a6fca16cb997596bcb8555d7327aafdb29f4683",
      "size": 888,
      "annotations": {
        "hook": "cat ${OSO_CACHE}/plugins.json | jq .",
        "org.opencontainers.image.title": "oso-legacy"
      }
    }
  ],
  "annotations": {
    "caveats": "to get auto-completions do this...",
    "description": "a bridge to the past",
    "hook": "echo installed in ${OSO_BIN}",
    "shortDescription": "a plugin"
  }
}
```

**Review by luisdavim — APPROVED** [review]
LGTM

**Comment by deitch** [comment]
@luisdavim let's continue the discussion on the issue #22

**Comment by deitch** [comment]
With #25 in, this has been rebased and is ready to go.

**Review by jdolitsky — APPROVED** [review]
👍

**Pull request merged**
