### PR TITLE
Prep for v1.0.0 release

### PR DESCRIPTION
**Pull request by jdolitsky**
- Update Go modules
- Update GitHub Actions to watch v1 branch
- Remove stability warning from README

### CODE REVIEW

**Review by sajayantony — APPROVED** [review]

**Comment by sajayantony** [comment]
@jdolitsky - Thank you for making this release happen.

**Comment by shizhMSFT** [comment]
@jdolitsky Recently, I've learnt that we can use `GITHUB_TOKEN` to do release instead of using our own PAT.

I've updated for https://github.com/notaryproject/notation/pull/135. Do you want to also apply that to `oras` and `oras-go`?

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Comment by jdolitsky** [comment]
@shizhMSFT - I think yes, absolutely, for releases with binaries.

In this case, since Go modules uses git, I will just create the tag

**Pull request merged**
