### PR TITLE
feat: support context cancellation in file store

### LINKED ISSUE #619: File store to support context cancel
[Adding a directory](https://github.com/oras-project/oras-go/blob/v2.3.0/content/file/file.go#L416) to `file.Store` could take a long time and sometimes users may want to cancel it.
Currently the `ctx` parameter is not used in the `Add` method and context cancel is not supported. We should consider adding this support for better user experience.
https://github.com/oras-project/oras-go/blob/47d028a52a21a2da888aa522543e99920d3f3ef7/content/file/file.go#L384-L385

### PR DESCRIPTION
**Pull request by lucasrod16**
Closes #619

### CODE REVIEW

**Review by Wwwsylvia — COMMENTED** [review]
@lucasrod16 Thank you for the contribution! Code changes LGTM. 
Can we add some unit tests and make sure the diff coverage reaches 80%?

**Comment by lucasrod16** [comment]
> @lucasrod16 Thank you for the contribution! Code changes LGTM. Can we add some unit tests and make sure the diff coverage reaches 80%?

Yes! I added a unit test for `tarDirectory`. I tried to verify the coverage locally use codecov-cli but ran into errors about requiring a token for uploading the report

**Review by Wwwsylvia — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Pull request merged**
