### PR TITLE
Update to Go 1.18

### PR DESCRIPTION
**Pull request by lucacome**
Bumps go to 1.18

### CODE REVIEW

**Comment by shizhMSFT** [comment]
Since this is library code, adopters may still use older golang versions. We need to be careful on bumping up go versions.

@jdolitsky @deitch @sajayantony @SteveLasker @feynmanzhou As a library, we should support a list of golang versions. For example, the last 2 - 3 versions.

**Comment by shizhMSFT** [comment]
Here's the reference for [go.mod](https://go.dev/doc/modules/gomod-ref).

The go version in the `go.mod` is _the minimum version of Go required by the current module_. I'd like to also mention that the go module with minimum requirement of 1.17 can be compiled against 1.18 and the resulted binary is in 1.18.

**Comment by shizhMSFT** [comment]
Linking #155

**Comment by shizhMSFT** [comment]
@lucacome Could you open an issue to justify the reason to bump up the minimum golang version requirement of `oras-go`? This is required by our [reviewing guide](https://github.com/oras-project/oras-go/blob/main/REVIEWING.md).

**Comment by lucacome** [comment]
> The go version in the `go.mod` is _the minimum version of Go required by the current module_. I'd like to also mention that the go module with minimum requirement of 1.17 can be compiled against 1.18 and the resulted binary is in 1.18.

It can also be the other way around, with the minimum of 1.18 it can be compiled against 1.17 if the library is not using anything specific to 1.18 (for example generics)

**Comment by lucacome** [comment]
I guess this was done in https://github.com/oras-project/oras-go/pull/270 🤷‍♂️

**Pull request closed without merging**
