### PR TITLE
[WIP] Re-tooling remotes resolver dependency

### PR DESCRIPTION
**Pull request by juliusl**
I am trying to decouple dependencies on containerd, to make the oras-go pkg a bit friendlier to take a dependency on. I'm starting on the resolver code since it is in the center of everything. And I plan on working my way towards images next. 

For implementing the resolver I am following the oci-spec  line by line, hence my notes in `http.go` (don't want to miss details). For auth, I started out with some basic oauth2 flows so that I can work without having to install docker.  I haven't put much thought into anything beyond that just yet. 

I have not started debugging this PR, but I'm anxious about getting too far ahead of myself so I wanted to put it up early. I'm pretty happy with the direction it's headed in so far, but I am open to discuss.

### CODE REVIEW

**Comment by deitch** [comment]
I am surprised this is as small as it is; I expected that retooling to be much bigger.

Speaking of which, is this compatible with our oras-go rewrite #8 ? @SteveLasker and @jdolitsky what is happening with getting that in?

**Comment by SteveLasker** [comment]
@deitch - https://github.com/oras-project/oras-go/pull/8#issuecomment-905691074

**Comment by SteveLasker** [comment]
Related to the registry testing/support: https://github.com/oras-project/artifacts-spec/issues/12
I'm not suggesting we implement the capabilities API, _yet_. Rather, see:

> ## Now or Later
> For the immediate timeframe, the ORAS libraries will likely just query if the referrers/ API exists to proxy the support of the artifacts.manifest.

**Comment by juliusl** [comment]
@SteveLasker no worries this will not diverge from #8, when that get's merged I'll spend time to ensure they integrate

**Comment by juliusl** [comment]
@SteveLasker re: capabilities, is it possible to add to that spec something analogous to the `GET /v2/`  check for the v2 registry api? 
For example `GET /oras/` (reference: https://github.com/opencontainers/distribution-spec/blob/main/spec.md#determining-support)

**Comment by bridgetkromhout** [comment]
Hi, @juliusl - please ensure you sign-off on your commits for the DCO bot. See https://github.com/oras-project/oras-go/pull/17/checks?check_run_id=3489560861 for details on how to fix it. Thanks.

**Comment by sajayantony** [comment]
I wanted to thank @juliusl for helping prototype this since it make a lot of the conversations about artifacts and discovery API happen. 
Also wanted to confirm if https://github.com/oras-project/oras-go/issues/63 will remove the depedency of containerd and we could close this PR as a part of PR pruning?

**Comment by SteveLasker** [comment]
+1 to pruning.

**Comment by shizhMSFT** [comment]
Closing this PR as #63 has been resolved.

**Comment by shizhMSFT** [comment]
Many thanks to @juliusl for helping investigating the possibilities on top of the `containerd`.

**Pull request closed without merging**
