### PR TITLE
chore: add .cover to ignore

### PR DESCRIPTION
**Pull request by TerryHowe**

### CODE REVIEW

**Review by Wwwsylvia — APPROVED** [review]
LGTM

**Comment by shizhMSFT** [comment]
@TerryHowe What is a `.cover` file? Is that a coverage file?

**Comment by TerryHowe** [comment]
> What is a .cover file? Is that a coverage file?

Yes, but now I don't see a coverage target in the Makefile, just a covhtml target. I had one for some reason.

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Pull request merged**
